name: bafna_vault
description: "Firebase-based document vault app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Packages
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.10

  # UI & State
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  lottie: ^2.7.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.1.0
  convex_bottom_bar: ^3.0.0
  animated_bottom_navigation_bar: ^1.1.0


  file_picker: ^8.0.3
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  open_file: ^3.3.2
  mime: ^1.0.4
  url_launcher: ^6.3.2
  device_info_plus: ^9.1.2
  file_saver: ^0.2.12
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png
    - assets/docs.json